# Generated by Django 6.0.2 on 2026-02-13 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('auth_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanned', 'Scanned'), ('authenticated', 'Authenticated'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance_bch',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance_sats',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['address'], name='wallet_wall_address_c7bf63_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_wall_user_id_03e396_idx'),
        ),
        migrations.AddField(
            model_name='walletsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='walletsession',
            index=models.Index(fields=['session_id'], name='wallet_wall_session_e5e3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='walletsession',
            index=models.Index(fields=['status', 'expires_at'], name='wallet_wall_status_f26908_idx'),
        ),
    ]
